### ISSUE TITLE
OSIA authentication service specifications

### ISSUE THREAD

**Issue by olivier-heurtier-sia** [GovStackWorkingGroup/BuildingBlockAPI#5]
OSIA has just published a [PR](https://github.com/SecureIdentityAlliance/osia/pull/57) with the definition of a new _authenticate_ service defined to suite the needs of GovStack.
This PR is open for comments.

**Comment by mcarlson** [comment]
Hello! In order to make this part of GovStack, we need to get a PR merged into from a fork of this repo. See https://github.com/GovStackWorkingGroup/BuildingBlockAPI/pull/11 for an example that does this. Thank you!
